# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
language: c
env:
  # Build and test against the master and devel branches of Nim
  - BRANCH=master
  - BRANCH=devel
compiler:
  # Build and test using both gcc and clang
  - gcc
  - clang
matrix:
  allow_failures:
    # Ignore failures when building against the devel Nim branch
    - env: BRANCH=devel
  fast_finish: true
install:
  - make -j
before_script:
    - export PATH="${PATH:+:$PATH}"
script:
    # Replace uppercase strings!
    #- nim c --cc:$CC --verbosity:0 -r MYFILE.nim
    # Optional: build docs.
    #- nim doc --docSeeSrcUrl:https://github.com/AUTHOR/MYPROJECT/blob/master --project MYFILE.nim
    - make hi
    - nim -h
cache:
  directories:
    - bin
branches:
  except:
    - gh-pages
